const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const people=[
{id:1,name:'林小满',role:'周末摄影爱好者',teach:'摄影',learn:'Python',cat:'艺术创作',desc:'告别自动模式。用自然光，拍出有故事感的人像和日常。',goal:'拍出一张自然光人像',mode:'线上',time:'周末下午',tint:'#fce9dd',ink:'#a36336'},
{id:2,name:'陈序',role:'独立开发者',teach:'Python',learn:'吉他',cat:'数码技术',desc:'从零写一个实用小程序，让重复的表格工作自动完成。',goal:'写出第一个自动化脚本',mode:'线上',time:'工作日晚上',tint:'#e7e9ff',ink:'#6264b9'},
{id:3,name:'阿泽',role:'弹了六年吉他的上班族',teach:'吉他',learn:'英语口语',cat:'艺术创作',desc:'不用先啃乐理，从四个和弦开始，弹唱你喜欢的第一首歌。',goal:'学会四个基础和弦',mode:'线下',time:'周末下午',tint:'#fff0cc',ink:'#967217'},
{id:4,name:'许知意',role:'英语交流爱好者',teach:'英语口语',learn:'摄影',cat:'语言交流',desc:'一起模拟旅行和日常聊天，开口比语法完美更重要。',goal:'完成一次英语自我介绍',mode:'线上',time:'工作日晚上',tint:'#dbf1f0',ink:'#357e78'},
{id:5,name:'周可可',role:'设计师 / 咖啡爱好者',teach:'咖啡手冲',learn:'Excel',cat:'生活方式',desc:'从磨豆到注水，找到适合自己的那杯咖啡。零基础也欢迎。',goal:'掌握一套基础手冲流程',mode:'线下',time:'周末上午',tint:'#f2e5d9',ink:'#926649'},
{id:6,name:'陆一',role:'互联网产品设计师',teach:'UI设计',learn:'Python',cat:'数码技术',desc:'用 Figma 把想法变成界面，一起完成你的第一个页面。',goal:'完成一个手机页面设计',mode:'线上',time:'周末下午',tint:'#f2e2f6',ink:'#9c5cab'},
{id:7,name:'唐可',role:'城市漫步记录者',teach:'摄影',learn:'Python',cat:'艺术创作',desc:'不需要昂贵相机，用手机练构图，把城市角落拍成你的作品。',goal:'学会三种手机构图方法',mode:'线上',time:'工作日晚上',tint:'#deedf9',ink:'#4a7f9e'},
{id:8,name:'苏晴',role:'数据分析师',teach:'Excel',learn:'健身',cat:'数码技术',desc:'学会数据透视表和常用函数，让每周的报表变得轻松。',goal:'独立制作一张数据透视表',mode:'线上',time:'周末下午',tint:'#e3f2df',ink:'#688d48'}];
'use strict';
const defaults={teach:'Python',learn:'摄影',time:'周末下午',mode:'线上',level:'熟练，可以带入门',goal:'一起写出第一个自动整理表格的小程序',published:false};
let raw=null;try{raw=localStorage.getItem('skillSwapV1')}catch{}
let state=SwapModel.restore(raw,defaults),view='discover',category='全部',selected=null,onlySaved=false,exchangeFilter='全部',reviewId=null;
const lessons={
  1:{about:'喜欢把周末留给相机和城市。更擅长边拍边讲，欢迎带着你拍过的照片一起讨论。',prep:'手机或相机均可；提前准备 2 张想改进的照片。',steps:['认识顺光、侧光和逆光','用一个场景练习人物构图','一起挑选照片并给出修改建议']},
  2:{about:'喜欢把重复工作变成小工具。先看你的实际需求，再一起拆成能实现的小步骤。',prep:'准备一台电脑；建议提前安装 Python，也可以使用在线练习环境。',steps:['理解变量与循环的用途','读取一份练习表格','完成一个整理数据的小脚本']},
  3:{about:'下班后的放松方式是弹唱。愿意陪零基础伙伴慢慢练，节奏可以根据你的情况调整。',prep:'自备吉他；线下地点需双方确认，优先公共排练空间。',steps:['认识琴弦与基础持琴姿势','练习 C、G、Am、F 和弦','尝试连贯弹奏一段副歌']},
  4:{about:'喜欢轻松对话式练习。会先听你说，再记录影响表达的几个小问题一起改。',prep:'准备一段简短自我介绍，列出一个最想练习的生活场景。',steps:['用英语做一分钟自我介绍','模拟一个旅行或生活场景','整理可复用的表达清单']},
  5:{about:'把冲咖啡当作观察和实验。一起用同一支豆子，对比水温和注水方式的差别。',prep:'线下选择公共咖啡空间；器材、咖啡豆及材料费用事先协商。',steps:['认识粉水比与研磨度','练习稳定注水','记录风味并调整下一杯配方']},
  6:{about:'做产品界面设计，也喜欢帮助新手把脑海里的点子做成可点击的页面。',prep:'准备电脑和 Figma 账号，带一个想做的小页面点子。',steps:['梳理页面目标与信息层级','搭建一个简单界面','连接按钮，完成交互原型']},
  7:{about:'随手拍也是一种观察生活的方法。不追求器材，从你每天经过的地方开始练习。',prep:'手机即可；准备一个方便拍摄的日常场景。',steps:['找出画面中的视觉重点','练习三分法与引导线','给一张照片做简单调色']},
  8:{about:'擅长把数据整理成一眼能懂的表格。用练习数据教学，避免使用真实工作敏感数据。',prep:'安装 Excel 或兼容表格软件；使用虚构或脱敏练习数据。',steps:['整理可分析的表格结构','创建并筛选数据透视表','用图表讲清一个数据结论']}
};
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',3600)}
function save(){try{localStorage.setItem('skillSwapV1',JSON.stringify(state));return true}catch{toast('浏览器未允许存储，本次修改无法在刷新后保留');return false}}
const assess=p=>SwapModel.assess(p,state.profile);
const match=p=>assess(p).mutual;
const esc=escapeHtml;
function resetFilters(){category='全部';onlySaved=false;$('#search').value='';$('#mode').value='all';$('#sort').value='recommended';syncFilters()}
function syncFilters(){$$('[data-cat]').forEach(b=>{b.classList.toggle('active',b.dataset.cat===category);b.setAttribute('aria-pressed',b.dataset.cat===category)});$('#savedOnly').setAttribute('aria-pressed',onlySaved);$('#savedOnly').classList.toggle('active',onlySaved);$('#savedOnly').textContent=`♡ 我的收藏 ${state.favorites.length}`}
function setView(value){if(!['discover','matches','exchanges'].includes(value))return;view=value;$$('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});render()}
function personCard(p){const a=assess(p),saved=state.favorites.includes(p.id);return `<article class="card"><div class="card-body"><div class="person"><div class="avatar" style="--tint:${p.tint};--ink:${p.ink}">${p.name[0]}</div><div><strong>${p.name}</strong><small>${p.role}</small></div><button class="bookmark ${saved?'saved':''}" data-save="${p.id}" aria-label="${saved?'取消收藏':'收藏'}${p.name}" aria-pressed="${saved}">${saved?'♥':'♡'}</button></div><div class="offer">我能教你 ${a.mutual?'<span class="badge">双向需要</span>':''}</div><h3>${p.teach}</h3><p class="desc">${p.desc}</p><div class="want">想交换 <b>${p.learn}</b></div><p class="meta">${p.mode}${p.mode==='线下'?' · 上海':''} · ${p.time}</p>${view==='matches'?`<div class="reason">匹配分 ${a.score}/100 · ${a.mutual?'双方技能需求吻合':'对方能教你想学的，回报内容待协商'}</div>`:''}</div><div class="card-bottom"><button class="text-button" data-detail="${p.id}">查看学习内容</button><button data-invite="${p.id}">发起交换 ↗</button></div></article>`}
function render(){document.body.dataset.view=view;const p=state.profile;$('#myTeach').textContent=p.teach;$('#myLearn').textContent=p.learn;$('#heroTeach').textContent=p.teach;$('#heroLearn').textContent=p.learn;$('#myTime').textContent=p.time+' · '+p.mode;$('#count').textContent=state.exchanges.filter(SwapModel.active).length;$('#filters').hidden=view==='exchanges';$('#exchangeOverview').hidden=view!=='exchanges';$('#resultTools').hidden=view==='exchanges';$('#matchNote').innerHTML='';$('#sectionTitle').textContent={discover:'发现你的技能搭子',matches:'为你找到的技能伙伴',exchanges:'我的交换计划'}[view];$('#sectionSub').textContent={discover:'先看看能一起完成什么，再决定和谁交换。',matches:'匹配理由看得见，时间与方式也要合得来。',exchanges:'从一个小目标开始，把每次交换变成真正的收获。'}[view];syncFilters();
if(view==='exchanges'){renderExchanges();return}
let list=people.filter(x=>(category==='全部'||x.cat===category)&&($('#mode').value==='all'||x.mode===$('#mode').value)&&SwapModel.normalize(x.teach+x.learn+x.name+x.cat).includes(SwapModel.normalize($('#search').value))&&(!onlySaved||state.favorites.includes(x.id)));
if(view==='matches'){list=list.filter(x=>assess(x).learns);const mutual=list.filter(match).length;$('#matchNote').innerHTML=`<div class="notice"><b>${esc(p.teach)} ⇄ ${esc(p.learn)}</b><br>当前筛选下有 ${mutual} 位双向匹配伙伴，${list.length-mutual} 位单向匹配伙伴（交换内容待协商）。<details><summary>匹配分怎么算？</summary><p>对方能教你想学的 +40，你能教对方想学的 +40，空闲时间相符 +10，交换方式相同 +10。满分 100；这是规则匹配分，不是成功概率。双方仍需确认实际安排。</p></details></div>`}
if($('#sort').value==='recommended')list.sort((a,b)=>assess(b).score-assess(a).score||a.id-b.id);else list.sort((a,b)=>a.id-b.id);
$('#resultCount').textContent=`${list.length} 位示例伙伴${onlySaved?' · 已收藏':''}`;
$('#results').innerHTML=list.map(personCard).join('')||`<div class="empty"><div class="empty-symbol">⇄</div><h3>${onlySaved?'还没有符合条件的收藏':'这次还没找到合适的伙伴'}</h3><p>${view==='matches'?'尝试“摄影”“Python”“吉他”等已有技能，或调整筛选。':'换一个关键词，或清除筛选后再看看。'}</p><div class="actions"><button class="outline" data-clear>清除筛选</button><button class="primary" data-publish>编辑技能名片</button></div></div>`;
if(view==='discover'&&p.published&&!$('#search').value&&category==='全部'&&!onlySaved&&($('#mode').value==='all'||$('#mode').value===p.mode))$('#results').insertAdjacentHTML('afterbegin',`<article class="card own-card"><div class="card-body"><span class="published">✓ 我的发布 · 仅本机可见</span><h3>${esc(p.teach)}</h3><p class="desc">${esc(p.goal||p.level)}</p><div class="want">想交换 <b>${esc(p.learn)}</b></div><p class="meta">${esc(p.time)} · ${esc(p.mode)}</p></div><div class="card-bottom"><span>已准备好分享</span><button data-publish>编辑名片</button></div></article>`)}
function openPublish(){const f=$('#publishForm');['teach','learn','time','mode','level','goal'].forEach(k=>f.elements[k].value=state.profile[k]||'');$('#publishDialog').showModal()}
function openDetail(id){const p=people.find(x=>x.id===Number(id));if(!p)return;const a=assess(p),l=lessons[p.id];$('#detailTitle').textContent=`和${p.name}学${p.teach}`;$('#detailContent').innerHTML=`<div class="detail-person"><div class="avatar" style="background:${p.tint};color:${p.ink}">${p.name[0]}</div><div><b>${p.role}</b><p class="meta">示例伙伴 · ${p.mode}${p.mode==='线下'?' · 上海':''} · ${p.time}</p></div></div><p>${l.about}</p><div class="detail-goal"><small>这一课，带走一个小成果</small><h3>${p.goal}</h3></div><h3>怎么一起学</h3><ol class="lesson-steps">${l.steps.map(s=>`<li>${s}</li>`).join('')}</ol><h3>开始前准备</h3><p>${l.prep}</p><div class="match-breakdown"><b>你们的匹配分 <span>${a.score}/100</span></b>${[[a.learns,'对方能教你想学的',40],[a.teaches,'你能教对方想学的',40],[a.time,'空闲时段相符',10],[a.mode,'交流方式一致',10]].map(([yes,label,n])=>`<div><span>${yes?'✓':'○'} ${label}</span><span>${yes?'+'+n:'待协商'}</span></div>`).join('')}<small>按技能、时段和方式计算，不代表交换成功概率。</small></div><p class="muted">${p.mode==='线下'?'线下交换请选择公共场所，出发前确认地点与材料安排。':'无需提前交换私人联系方式，先把学习目标和时间说清楚。'}</p><div class="actions"><button class="outline" data-save="${p.id}">${state.favorites.includes(p.id)?'♥ 已收藏':'♡ 收藏伙伴'}</button><button class="primary" data-invite="${p.id}">和${p.name}发起交换</button></div>`;$('#detailDialog').showModal()}
function openInvite(id){selected=people.find(p=>p.id===Number(id));if(!selected)return;if($('#detailDialog').open)$('#detailDialog').close();const a=assess(selected);$('#inviteTitle').textContent='和'+selected.name+'换个本事';$('#inviteSummary').textContent='你分享 '+state.profile.teach+' ⇄ 你学习 '+selected.teach;$('#inviteCompatibility').textContent=a.mutual?'双方技能需求吻合。先约一次轻量体验，合适再继续。':`对方目前想学${selected.learn}，与你分享的${state.profile.teach}不同。可以创建待协商邀约，先确认对方是否感兴趣。`;const f=$('#inviteForm');f.elements.goal.value=selected.goal;f.elements.time.value=selected.time;f.elements.message.value='';$('#inviteDialog').showModal()}
function renderExchanges(){const finished=state.exchanges.filter(x=>x.status==='已完成');$('#exchangeStats').innerHTML=`<div><strong>${state.exchanges.filter(SwapModel.active).length}</strong><span>进行中的交换</span></div><div><strong>${finished.length}</strong><span>完成的小目标</span></div><div><strong>${finished.reduce((n,x)=>n+(parseInt(x.duration)||30),0)}</strong><span>累计学习分钟</span></div>`;$$('[data-exchange-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.exchangeFilter===exchangeFilter);b.setAttribute('aria-pressed',b.dataset.exchangeFilter===exchangeFilter)});const list=state.exchanges.filter(x=>exchangeFilter==='全部'||(exchangeFilter==='进行中'?SwapModel.active(x):x.status===exchangeFilter));$('#results').innerHTML=list.map(exchangeCard).join('')||`<div class="empty"><div class="empty-symbol">↗</div><h3>${state.exchanges.length?'这个分类还没有交换记录':'第一次交换，从一个小目标开始'}</h3><p>浏览伙伴的学习内容，再发起一次 30 分钟的交换。</p><button class="primary" data-discover>去发现技能</button></div>`}
function exchangeCard(x){const checks=x.checks||[false,false,false],done=checks.filter(Boolean).length;return `<article class="card exchange"><div class="exchange-heading"><span class="status status-${x.status==='已完成'?'done':x.status==='已取消'?'cancelled':'active'}">${esc(x.status)}</span><span class="meta">与 ${esc(x.name)} · 演示交换</span></div><h3>${esc(x.teach)} <span class="swap-inline">⇄</span> ${esc(x.learn)}</h3><p class="exchange-goal">${esc(x.goal)}</p><div class="want">${esc(x.time)} · 双方各 ${esc(x.duration)} · ${esc(x.mode)}</div>${x.message?`<p class="message-preview">你的留言：${esc(x.message)}</p>`:''}${x.status==='已约定'?`<div class="learning-plan"><div class="plan-heading"><b>本次学习计划</b><span>${done}/3 已完成</span></div><progress max="3" value="${done}" aria-label="本次学习进度"></progress>${['准备好学习材料与要讨论的问题',`完成双方各 ${x.duration} 的分享与练习`,'回顾学习目标，给彼此一个具体建议'].map((s,i)=>`<label class="check-row"><input type="checkbox" data-check="${esc(x.id)}" data-step="${i}" ${checks[i]?'checked':''}><span>${esc(s)}</span></label>`).join('')}<p class="muted">勾选实际完成的步骤，三个步骤完成后可结束交换。</p></div>`:''}${x.status==='已完成'?`<div class="review-preview"><b>${x.note?'我的学习复盘':'留下一点收获，方便下次回看'}</b>${x.rating?`<span class="stars">${'★'.repeat(x.rating)}${'☆'.repeat(5-x.rating)}</span>`:''}<p>${x.note?esc(x.note):'记录今天学会了什么，以及还想练习什么。'}</p></div>`:''}<div class="actions">${x.status==='待回应'?`<button class="primary" data-progress="${esc(x.id)}">模拟对方接受</button><span class="muted">示例伙伴不会真实回复</span>`:x.status==='已约定'?`<button class="primary" data-progress="${esc(x.id)}" ${done<3?'disabled':''}>完成本次交换</button>`:x.status==='已完成'?`<button class="outline" data-review="${esc(x.id)}">${x.note?'编辑学习复盘':'记录学习复盘'}</button>`:''}${SwapModel.active(x)?`<button class="text-button" data-cancel="${esc(x.id)}">取消邀约</button>`:''}</div></article>`}
function openReview(id){const x=state.exchanges.find(x=>x.id===id);if(!x||x.status!=='已完成')return;reviewId=id;$('#reviewGoal').textContent=x.goal;$('#reviewForm').elements.note.value=x.note||'';$('#reviewForm').elements.rating.value=String(x.rating||5);$('#reviewDialog').showModal()}
function toggleFavorite(id){id=Number(id);if(!people.some(p=>p.id===id))return;const exists=state.favorites.includes(id);state.favorites=exists?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render();if($('#detailDialog').open){$('#detailDialog').close();openDetail(id)}toast(exists?'已取消收藏':'已收藏，可在“我的收藏”中查看')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-publish'))openPublish();if(b.dataset.view)setView(b.dataset.view);if(b.hasAttribute('data-discover')){resetFilters();setView('discover')}if(b.hasAttribute('data-clear')){resetFilters();render()}if(b.dataset.cat){category=b.dataset.cat;render()}if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.detail)openDetail(b.dataset.detail);if(b.dataset.invite)openInvite(b.dataset.invite);if(b.dataset.save)toggleFavorite(b.dataset.save);if(b.dataset.exchangeFilter){exchangeFilter=b.dataset.exchangeFilter;render()}if(b.dataset.progress){const i=state.exchanges.findIndex(x=>x.id===b.dataset.progress);if(i<0)return;try{state.exchanges[i]=SwapModel.advance(state.exchanges[i]);if(state.exchanges[i].status==='已完成')exchangeFilter='已完成';save();render();toast(state.exchanges[i].status==='已完成'?'交换完成！记录一下今天的收获吧':'已模拟接受，学习计划已生成')}catch(error){toast(error.message)}}if(b.dataset.cancel){const x=state.exchanges.find(x=>x.id===b.dataset.cancel);if(x&&SwapModel.active(x)){$('#cancelDialog').dataset.exchangeId=x.id;$('#cancelPartner').textContent=x.name;$('#cancelDialog').showModal()}}if(b.dataset.review)openReview(b.dataset.review)});
document.addEventListener('change',e=>{if(!e.target.matches('[data-check]'))return;const x=state.exchanges.find(x=>x.id===e.target.dataset.check),step=Number(e.target.dataset.step);if(x?.status==='已约定'&&Number.isInteger(step)&&step>=0&&step<3){x.checks[step]=e.target.checked;save();render();const checkbox=$(`[data-check="${CSS.escape(x.id)}"][data-step="${step}"]`);checkbox?.focus()}});
$('#search').addEventListener('input',render);$('#mode').addEventListener('change',render);$('#sort').addEventListener('change',render);$('#savedOnly').addEventListener('click',()=>{onlySaved=!onlySaved;render()});$('.brand').addEventListener('click',e=>{e.preventDefault();setView('discover')});
$('#confirmCancel').addEventListener('click',()=>{const x=state.exchanges.find(x=>x.id===$('#cancelDialog').dataset.exchangeId);if(x&&SwapModel.active(x)){x.status='已取消';save();render();toast('邀约已取消，记录仍会保留')}$('#cancelDialog').close()});
$('#publishForm').addEventListener('submit',e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.teach=p.teach.trim();p.learn=p.learn.trim();if(!p.teach||!p.learn){toast('请填写你能教和想学的技能');return}if(SwapModel.skill(p.teach)===SwapModel.skill(p.learn)){toast('能教和想学的技能相同，请换一个学习目标');return}state.profile={...p,published:true};save();$('#publishDialog').close();resetFilters();setView('matches');toast('技能名片已保存，为你更新了匹配结果')});
$('#inviteForm').addEventListener('submit',e=>{e.preventDefault();if(!selected)return;const f=Object.fromEntries(new FormData(e.target));f.goal=f.goal.trim();f.message=f.message.trim();if(!f.goal){toast('请填写学习目标');return}if(state.exchanges.some(x=>x.personId===selected.id&&SwapModel.active(x))){$('#inviteDialog').close();exchangeFilter='进行中';setView('exchanges');toast('与这位伙伴已有进行中的邀约');return}state.exchanges.unshift({id:crypto.randomUUID(),personId:selected.id,name:selected.name,teach:state.profile.teach,learn:selected.teach,mode:selected.mode,...f,status:'待回应',checks:[false,false,false],note:'',rating:0,createdAt:new Date().toISOString()});save();$('#inviteDialog').close();exchangeFilter='进行中';setView('exchanges');toast('演示邀约已创建，可模拟对方接受')});
$('#reviewForm').addEventListener('submit',e=>{e.preventDefault();const x=state.exchanges.find(x=>x.id===reviewId);if(!x||x.status!=='已完成')return;const f=new FormData(e.target);x.note=String(f.get('note')).trim();if(!x.note){toast('写下至少一点学习收获吧');return}x.rating=Number(f.get('rating'));save();$('#reviewDialog').close();render();toast('复盘已保存，仅你在本浏览器可见')});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'show_skill_matches',title:'查看技能匹配',description:'清除筛选并打开匹配页，返回匹配理由和规则分；不创建邀约。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected empty object');resetFilters();setView('matches');return{partners:people.filter(p=>assess(p).learns).map(p=>({name:p.name,teach:p.teach,learn:p.learn,...assess(p)}))}}})).catch(()=>{})}catch{}}
render();



