const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const people=[
{id:1,name:'林小满',role:'周末摄影爱好者',teach:'摄影',learn:'Python',cat:'艺术创作',desc:'告别自动模式。用自然光，拍出有故事感的人像和日常。',goal:'拍出一张自然光人像',mode:'线上',time:'周末下午',tint:'#fce9dd',ink:'#a36336'},
{id:2,name:'陈序',role:'独立开发者',teach:'Python',learn:'吉他',cat:'数码技术',desc:'从零写一个实用小程序，让重复的表格工作自动完成。',goal:'写出第一个自动化脚本',mode:'线上',time:'工作日晚上',tint:'#e7e9ff',ink:'#6264b9'},
{id:3,name:'阿泽',role:'弹了六年吉他的上班族',teach:'吉他',learn:'英语口语',cat:'艺术创作',desc:'不用先啃乐理，从四个和弦开始，弹唱你喜欢的第一首歌。',goal:'学会四个基础和弦',mode:'线下',time:'周末下午',tint:'#fff0cc',ink:'#967217'},
{id:4,name:'许知意',role:'英语交流爱好者',teach:'英语口语',learn:'摄影',cat:'语言交流',desc:'一起模拟旅行和日常聊天，开口比语法完美更重要。',goal:'完成一次英语自我介绍',mode:'线上',time:'工作日晚上',tint:'#dbf1f0',ink:'#357e78'},
{id:5,name:'周可可',role:'设计师 / 咖啡爱好者',teach:'咖啡手冲',learn:'Excel',cat:'生活方式',desc:'从磨豆到注水，找到适合自己的那杯咖啡。零基础也欢迎。',goal:'掌握一套基础手冲流程',mode:'线下',time:'周末上午',tint:'#f2e5d9',ink:'#926649'},
{id:6,name:'陆一',role:'互联网产品设计师',teach:'UI设计',learn:'Python',cat:'数码技术',desc:'用 Figma 把想法变成界面，一起完成你的第一个页面。',goal:'完成一个手机页面设计',mode:'线上',time:'周末下午',tint:'#f2e2f6',ink:'#9c5cab'},
{id:7,name:'唐可',role:'城市漫步记录者',teach:'摄影',learn:'Python',cat:'艺术创作',desc:'不需要昂贵相机，用手机练构图，把城市角落拍成你的作品。',goal:'学会三种手机构图方法',mode:'线上',time:'工作日晚上',tint:'#deedf9',ink:'#4a7f9e'},
{id:8,name:'苏晴',role:'数据分析师',teach:'Excel',learn:'健身',cat:'数码技术',desc:'学会数据透视表和常用函数，让每周的报表变得轻松。',goal:'独立制作一张数据透视表',mode:'线上',time:'周末下午',tint:'#e3f2df',ink:'#688d48'}];
const defaults={teach:'Python',learn:'摄影',time:'周末下午',mode:'线上',level:'熟练，可以带入门',goal:'一起写出第一个自动整理表格的小程序',published:false};let state={profile:{...defaults},exchanges:[]};try{const stored=JSON.parse(localStorage.getItem('skillSwapV1'));if(stored&&typeof stored.profile?.teach==='string'&&Array.isArray(stored.exchanges))state=stored}catch{}let view='discover',category='全部',selected=null;function save(){try{localStorage.setItem('skillSwapV1',JSON.stringify(state))}catch{toast('浏览器未允许存储，当前修改仅在本次访问有效')}}function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',3500)}
const norm=s=>s.trim().toLowerCase();const same=(a,b)=>norm(a)===norm(b);const match=p=>same(p.teach,state.profile.learn)&&same(p.learn,state.profile.teach);const score=p=>(same(p.teach,state.profile.learn)?2:0)+(same(p.learn,state.profile.teach)?2:0)+(p.mode===state.profile.mode?1:0)+(p.time===state.profile.time?1:0);
function setView(v){view=v;$$('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.view===v);b.setAttribute('aria-current',b.dataset.view===v?'page':'false')});render()}
function card(p){const perfect=match(p);return `<article class="card"><div class="card-body"><div class="person"><div class="avatar" style="--tint:${p.tint};--ink:${p.ink}">${escapeHtml(p.name.slice(0,1))}</div><div><strong>${escapeHtml(p.name)}</strong><small>${p.role}</small></div>${perfect?'<span class="match-label">双向匹配</span>':''}</div><div class="offer">我能教你</div><h3>${p.teach}</h3><p class="desc">${p.desc}</p><div class="want">想交换 <b>${p.learn}</b></div>${view==='matches'?`<div class="reason">${perfect?'✓ 双方技能需求吻合':'可以教你想学的，交换内容待协商'}${p.time===state.profile.time?' · 时间一致':''}${p.mode===state.profile.mode?' · 方式一致':''}</div>`:''}</div><div class="card-bottom"><span>${p.mode==='线上'?'◉':'⌖'} ${p.mode}${p.mode==='线下'?' · 上海':''} · ${p.time}</span><button data-invite="${p.id}">聊聊交换 ↗</button></div></article>`}
function render(){const p=state.profile;$('#myTeach').textContent=p.teach;$('#myLearn').textContent=p.learn;$('#myTime').textContent=p.time+' · '+p.mode;$('#count').textContent=state.exchanges.length;$('#filters').hidden=view==='exchanges';$('#matchNote').innerHTML='';$('#sectionTitle').textContent={discover:'发现你的技能搭子',matches:'为你找到的技能伙伴',exchanges:'我的交换计划'}[view];$('#sectionSub').textContent={discover:'从兴趣出发，让学习多一种可能。',matches:'优先双向需求，再看时间和交流方式。',exchanges:'把想学的技能，变成下一次小小进步。'}[view];
if(view==='exchanges'){renderExchanges();return}let list=people.filter(p=>(category==='全部'||p.cat===category)&&($('#mode').value==='all'||p.mode===$('#mode').value)&&norm(p.teach+p.learn+p.name).includes(norm($('#search').value)));if(view==='matches'){list=list.filter(p=>same(p.teach,state.profile.learn)).sort((a,b)=>score(b)-score(a));$('#matchNote').innerHTML=`<div class="notice">你能教 <b>${escapeHtml(p.teach)}</b>，想学 <b>${escapeHtml(p.learn)}</b>。找到 ${people.filter(match).length} 位双向需求吻合的示例伙伴。</div>`}$('#results').innerHTML=list.map(card).join('')||'<div class="empty"><h3>暂时还没找到合适的伙伴</h3><p>试试其他关键词，或调整你的技能名片。</p><button class="outline" data-publish>调整技能名片</button></div>';if(view==='discover'&&p.published&&!$('#search').value&&category==='全部'&&($('#mode').value==='all'||$('#mode').value===p.mode))$('#results').insertAdjacentHTML('afterbegin',`<article class="card"><div class="card-body"><span class="published">✓ 我的发布 · 仅本机可见</span><h3>${escapeHtml(p.teach)}</h3><p class="desc">${escapeHtml(p.goal||p.level)}</p><div class="want">想交换 <b>${escapeHtml(p.learn)}</b></div></div><div class="card-bottom"><span>${escapeHtml(p.mode)} · ${escapeHtml(p.time)}</span><button data-publish>编辑名片</button></div></article>`)}
function renderExchanges(){$('#results').innerHTML=state.exchanges.length?state.exchanges.map(x=>`<article class="card exchange"><div><span class="status">${escapeHtml(x.status)}</span><span class="meta">　与 ${escapeHtml(x.name)} 的演示交换</span></div><h3>${escapeHtml(x.teach)} ⇄ ${escapeHtml(x.learn)}</h3><p class="desc">学习目标：${escapeHtml(x.goal)}</p><div class="want">${escapeHtml(x.time)} · 每人 ${escapeHtml(x.duration)} · ${escapeHtml(x.mode)}</div><div class="actions">${x.status==='待回应'?`<button class="primary" data-progress="${x.id}">模拟对方接受</button>`:x.status==='已约定'?`<button class="primary" data-progress="${x.id}">标记交换完成</button>`:x.status==='已完成'?'<span class="reason">✓ 又学会了一点新本事！</span>':''}${['待回应','已约定'].includes(x.status)?`<button class="outline" data-cancel="${x.id}">取消邀约</button>`:''}</div></article>`).join(''):'<div class="empty"><h3>第一次交换，从打个招呼开始</h3><p>找到合适的技能伙伴，为彼此定一个小目标。</p><button class="primary" data-discover>去发现技能</button></div>'}
function openPublish(){const f=$('#publishForm');['teach','learn','time','mode','level','goal'].forEach(k=>f.elements[k].value=state.profile[k]||'');$('#publishDialog').showModal()}
function openInvite(id){selected=people.find(p=>p.id===Number(id));if(!selected)return;$('#inviteTitle').textContent='和'+selected.name+'换个本事';$('#inviteSummary').textContent='你分享 '+state.profile.teach+' ⇄ 你学习 '+selected.teach;$('#inviteForm').elements.goal.value=selected.goal;$('#inviteForm').elements.time.value=selected.time;$('#inviteDialog').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-publish'))openPublish();if(b.dataset.view)setView(b.dataset.view);if(b.hasAttribute('data-discover'))setView('discover');if(b.dataset.cat){category=b.dataset.cat;$$('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));render()}if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.invite)openInvite(b.dataset.invite);if(b.dataset.progress){const x=state.exchanges.find(x=>x.id===b.dataset.progress);if(x)x.status=x.status==='待回应'?'已约定':'已完成';save();render();toast('交换进度已更新')}if(b.dataset.cancel){const x=state.exchanges.find(x=>x.id===b.dataset.cancel);if(x)x.status='已取消';save();render();toast('邀约已取消')}});$('#search').addEventListener('input',render);$('#mode').addEventListener('change',render);$('.brand').addEventListener('click',e=>{e.preventDefault();setView('discover')});
$('#publishForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),p=Object.fromEntries(f);p.teach=p.teach.trim();p.learn=p.learn.trim();if(!p.teach||!p.learn){toast('请填写你能教和想学的技能');return}state.profile={...p,published:true};save();$('#publishDialog').close();$('#search').value='';$('#mode').value='all';category='全部';$$('[data-cat]').forEach(b=>b.classList.toggle('active',b.dataset.cat==='全部'));setView('matches');toast('技能名片已保存，来看看匹配伙伴吧')});
$('#inviteForm').addEventListener('submit',e=>{e.preventDefault();if(!selected)return;const f=Object.fromEntries(new FormData(e.target));if(!f.goal.trim()){toast('请填写学习目标');return}const exists=state.exchanges.some(x=>x.personId===selected.id&&['待回应','已约定'].includes(x.status));if(exists){$('#inviteDialog').close();setView('exchanges');toast('你已经有一条与这位伙伴进行中的邀约');return}state.exchanges.unshift({id:crypto.randomUUID(),personId:selected.id,name:selected.name,teach:state.profile.teach,learn:selected.teach,mode:selected.mode,...f,status:'待回应'});save();$('#inviteDialog').close();setView('exchanges');toast('演示邀约已创建，可模拟对方接受')});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'show_skill_matches',title:'查看技能匹配',description:'切换到匹配页面，返回当前名片的双向匹配伙伴，不创建邀约。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty object');setView('matches');return{partners:people.filter(match).map(p=>({name:p.name,teach:p.teach,learn:p.learn}))}}})).catch(()=>{})}catch{}}
render();
